# Generated by Django 2.2.2 on 2019-07-05 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0009_remove_modelimportattempt_acknowledged'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelImporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'pending'), (1, 'empty'), (2, 'deleted'), (3, 'created_clean'), (4, 'created_dirty'), (5, 'rejected')], db_index=True, default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Model Importer',
                'verbose_name_plural': 'Model Importers',
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddField(
            model_name='modelimportattempt',
            name='model_importer',
            field=models.ForeignKey(default=-1, help_text='Reference to the ModelImporter that made this attempt', on_delete=django.db.models.deletion.CASCADE, related_name='model_import_attempts', to='django_import_data.ModelImporter'),
            preserve_default=False,
        ),
    ]
